### ISSUE TITLE
Mistral Support

### ISSUE THREAD

**Issue by fakerybakery** [IST-DASLab/sparsegpt#26]
Hi,
Does this project support Mistral?
Thanks!

**Comment by pprp** [comment]
No actually, I got error: 

```
Traceback (most recent call last):
  File "main.py", line 118, in <module>
    main()
  File "main.py", line 90, in main
    prune_sparsegpt(args, model, tokenizer, device, prune_n=prune_n, prune_m=prune_m, layer_no=idx)
  File "/home/user/miniconda3/envs/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data2/user/workspace/PRUNE/GBLM-Pruner/lib/prune.py", line 513, in prune_sparsegpt
    gpts[name].fasterprune(args.sparsity_ratio, prune_n=prune_n, prune_m=prune_m, percdamp=0.01, blocksize=128)
  File "/data2/user/workspace/PRUNE/GBLM-Pruner/lib/sparsegpt.py", line 66, in fasterprune
    H = torch.linalg.cholesky(H)
torch._C._LinAlgError: linalg.cholesky: The factorization could not be completed because the input is not positive-definite (the leading minor of order 1 is not positive-definite).
```

**Comment by bhavyashahh** [comment]
Try to increase the dampening factor (cdamp) to avoid this non positive definite issue of the Hession matrix.
