### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by thistleknot** [IST-DASLab/sparsegpt#35]
```
(textgen) [root@pve-m7330 sparsegpt]# python llama.py ../text-generation-webui/models/TinyLlama-1.1B-Chat-v1.0/ wikitext2 --nsamples 10
Token indices sequence length is longer than the specified maximum sequence length for this model (2824491 > 2048). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (2824491 > 2048). Running this sequence through the model will result in indexing errors
Dataset: wikitext2
Evaluating ...
0
Traceback (most recent call last):
  File "/home/user/sparsegpt/llama.py", line 335, in <module>
    llama_eval(model, testloader, DEV, dataset, args.log_wandb)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/sparsegpt/llama.py", line 211, in llama_eval
    outs[j] = layer(inps[j].unsqueeze(0), attention_mask=attention_mask)[0]
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 739, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 644, in forward
    cos, sin = self.rotary_emb(value_states, position_ids)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 134, in forward
    inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1)
AttributeError: 'NoneType' object has no attribute 'shape'
(textgen) [root@pve-m7330 sparsegpt]#

```

**Comment by phind-justin** [comment]
same

**Comment by phind-justin** [comment]
wondering if this is a transformers version issue

**Comment by algorithmexplorer** [comment]
outs[j] = layer(inps[j].unsqueeze(0), attention_mask=attention_mask)[0]
这一行代码没有加位置编码。更改之后是这样的
outs[j] = layer(inps[j].unsqueeze(0), attention_mask=attention_mask, position_ids=cache_position)[0]
@phind-justin @thistleknot

**Comment by hktk07** [comment]
I have the same question and I just use the code "
model = AutoModelForCausalLM.from_pretrained('llama2')
c_loss, m_loss = model(examples, labels, observations)",and it all make mistake in library function

**Comment by SHUSHENGQIGUI** [comment]
> wondering if this is a transformers version issue

hi you can refer the code fo wanda: https://github.com/locuslab/wanda/blob/main/lib/prune.py，modify function of llama.py as prune_sparsegpt()

**Comment by SHUSHENGQIGUI** [comment]
> hi you can refer the code fo wanda: [https://github.com/locuslab/wanda/blob/main/lib/prune.py，modify](https://github.com/locuslab/wanda/blob/main/lib/prune.py%EF%BC%8Cmodify) function of llama.py as prune_sparsegpt()

hi you can refer the code fo wanda: [https://github.com/locuslab/wanda/blob/main/lib/prune.py](https://github.com/locuslab/wanda/blob/main/lib/prune.py) , modify function of llama.py as prune_sparsegpt()

**Comment by time-less-ness** [comment]
I get this same error trying locally.

```
(venv)$ python llama.py  /data/Llama3-ChatQA-1.5-8B   c4 --sparsity 0.5
...
  File "sparsegpt/venv/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 110, in forward
    inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1)
                                                                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by minions0816** [comment]
> outs[j] = layer(inps[j].unsqueeze(0), attention_mask=attention_mask)[0] 这一行代码没有加位置编码。更改之后是这样的 outs[j] = layer(inps[j].unsqueeze(0), attention_mask=attention_mask, position_ids=cache_position)[0] @phind-justin @thistleknot

cache position 是什么

**Comment by minions0816** [comment]
@algorithmexplorer cache_position是啥

**Comment by SimWangArizona** [comment]
Hi! If you are running squeeze LLM and have the same issue, this may be useful.
The issue can be attributed to the **null position_ids**.
First, at llama.py, check class "class Catcher(nn.Module):", in the original code, it is like this:
![image](https://github.com/user-attachments/assets/17fb5e47-53e5-433e-81e1-7a26a0b260cb)
And position ids are obtained by:
![image](https://github.com/user-attachments/assets/420555a5-faa5-4f55-b498-cea883e4c648)
But after I read the code of GPTQ for llama, which runs well with llama. It is written like this:
![image](https://github.com/user-attachments/assets/337fe1e7-7717-4897-8816-ec72fb362976)
And
![image](https://github.com/user-attachments/assets/0cf28d02-ece8-42e7-b267-dc35cc47623d)
After changing them, I finnaly obtain the position_ids, which is a 2048 size torch.tensor. Please also **make ture** that the "try" command runs well, because this will affect the size of position_ids (not run will come up with size does not match error(4096 vs. 2048)).
![image](https://github.com/user-attachments/assets/4a528912-3ea0-44b1-9f81-28fe62850735)
Did not know the real reason, but works for me.

**Comment by jimmy-adams** [comment]
> I have the same question and I just use the code " model = AutoModelForCausalLM.from_pretrained('llama2') c_loss, m_loss = model(examples, labels, observations)",and it all make mistake in library function 只有“c_loss, m_loss = model(examples, labels, observations)”是自己写的代码报错，其他都是库函数报错

请问后面这个问题解决了吗
